title: Dayton Valley Aquaponics
email: pete@laxaltandmciver.co
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://dvaquaponics.com"
url: "http://dvaquaponics.com"

# Glynn FTP Deploy Settings
ftp_host: 'dvaquaponics.com'
ftp_dir: '/public_html/'
ftp_passive: false
ftp_port: 21
ftp_username: 'lm@dvaquaponics.com'
ftp_password: 'Unlimited2!'

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
